# version: '3'
# services:
  # web:
    # build: ./web
    # ports:
    # - "80:80"
    # expose 80 on host and sent to 80 in container
    # volumes:
    # - ./web:/usr/share/nginx/html
  version: '3.5' # We use version 3.5 syntax # specify docker-compose version

  # Define the services/containers to be run
  services:
    angular: # name of the first service
      # container_name: angularcontainer  # Container name
      build: ./angular-form # specify the directory of the Dockerfile
      volumes: # Volume binding
        - './angular-form:/usr/src/app' 
      ports:
        - "80:80" # specify port forewarding
  # version: '3.0' # specify docker-compose version
 
  # Define the services/ containers to be run
  # services:
  #  angular: # name of the first service
  #   build: ./angular-form # specify the directory of the Dockerfile
  #   ports:
  #   - "4200:4200" # specify port mapping
   
  #  express: # name of the second service
  #   build: express-server # specify the directory of the Dockerfile
  #   ports:
  #   - "3000:3000" #specify ports mapping
  #   links:
  #   - database # link this service to the database service
   
  #  database: # name of the third service
  #   image: mongo # specify image to build container from
  #   ports:
  #   - "27017:27017" # specify port forwarding


     
