version: '3'
services:
  web:
    build: ./web
    ports:
    - "80:80"
    # expose 80 on host and sent to 80 in container
    volumes:
    - ./web:/usr/share/nginx/html
    
#   nginx:
#     image: nginx
